development:
  adapter: postgresql
  database: radiodepaul
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1

test:
  adapter: postgresql
  database: radiodepaul_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1

production:
  adapter: postgresql
  database: radiodepaul
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
